### ISSUE TITLE
Create test environment setup docs

### ISSUE THREAD

**Issue by nrwahl2** [oresat/oresat-live-software#11]
The steps and requirements to create an end-to-end test environment for OreSat Live are stored largely in the form of scattered notes and tribal knowledge. We should have an easily accessible and well-formatted document that walks through the entire process:
* Required hardware (including known working models)
  * BeagleBone Black (to emulate on-satellite board)
  * Raspberry Pi (to emulate handheld ground station (HGS))
    * Some notes recommend a Pi Zero, but it has only one USB port. Ryan and I were unable to access it while it had a WiFi adapter attached. There may be a way, but it doesn't seem straightforward. Get a more capable model if possible.
  * USB camera (Sony IMX214?)
  * Two (2) USB WiFi adapters (Atheros AR9721)
  * USB hub
  * USB cables (check types)
  * Two (2) micro-SD cards
* Hardware setup
  * We should have detailed instructions on how all hardware components are connected.
* Software setup
  * `oresat-dev` image (at least for now)
  * How to obtain image and write to both devices' SD cards
  * Perform any required networking setup
  * Update packages
  * Install dependencies that aren't in the `oresat-dev` image
    * `build-essential`
    * `firmware-ath9k-htc` for the AR9271 radio
    * `libglib2.0-dev` to build the `camera` component
      * Note: Dependency on `libglib2.0-dev` is planned but does not exist at the time of writing.
  * Clone repos
    * `oresat-libdxwifi`
    * `oresat-live-software`
    * Probably `oresat-dxwifi-software`
  * Build the software
  * Test image capture
  * There are tests in Russell's notes about sending files, remote tunneling, and "test check"... need to clarify what these are supposed to do.
* Rocket Room
  * Ideally, we should expand this documentation to cover setting up the test bench on the Rocket Room's `oresat` VPN, so that it's accessible remotely. This was a bit of a pain from the perspective of both hardware and software, and Ryan did almost all of the work.

Existing notes:
* https://docs.google.com/document/d/1Plt5QjwKvtl5WflxNVBm4L9sDN4x5324ssn_EeqEeBs/edit?pli=1

**Comment by sashetov** [comment]
work in progress document (readonly):
https://docs.google.com/document/d/1PQFcQvY8KZXJjFgdfzLHsgyyor7YhBfAwqPasGg-Mck/edit?usp=sharing

**Comment by nrwahl2** [comment]
Closed via the READMEs in the oresat-dxwifi-software and oresat-live-software repos
