### ISSUE TITLE
Create image for handheld ground station (HGS)

### ISSUE THREAD

**Issue by nrwahl2** [oresat/oresat-live-software#12]
The image should contain everything that is required to run the OreSat Live HGS, without any unnecessary components.

Create a new issue to package OreSat software for the HGS if necessary, and install those package(s) in the image.

Make an attempt to verify which non-OreSat packages are actually required, and remove if unnecessary.

**Comment by sashetov** [comment]
updated package for live station hgs .deb to support writing mp4's via rx to video dir.
have tested and confirmed it works
here's the PR: https://github.com/oresat/oresat-live-software/pull/21/

**Comment by sashetov** [comment]
I also an image for HGS ready with all the relevant packages installed but I need to know how to upload it ot the relevant repository

**Comment by sashetov** [comment]
PR #22 is now available, with new package version for HGS web service and RX service

**Comment by sashetov** [comment]
I did upload it to deb-builder server on the oresat network. the image is bigger than previous -dev image instances, though
but this is basically it:
```
oresat@deb-builder:~ $ ls -la oresat-dev-2023-08-23.img*
-rw-r--r-- 1 oresat oresat 1520745187 Aug 15 05:24 oresat-dev-2023-08-23.img.zst
-rw-r--r-- 1 oresat oresat         96 Aug 15 05:42 oresat-dev-2023-08-23.img.zst.sha256
```

I think the other images might have been built via tools from the oresat-linux repo, ex:
```
oresat@deb-builder:~ $ ls -la oresat-dev-2023-07-30-2gb*
-rw-r--r-- 1 oresat oresat 607467302 Jul 30 20:22 oresat-dev-2023-07-30-2gb.img.zst
-rw-r--r-- 1 oresat oresat       100 Jul 30 20:24 oresat-dev-2023-07-30-2gb.img.zst.sha256
```


anyway, I didn't see any .deb images there, so wont upload any

**Comment by sashetov** [comment]
I've asked in internal slack on how to build these images and debs correctly, so maybe hold off on closing this, for now. Otherwise, that aside, I think this task is done.
